# Generated by Django 4.0.1 on 2022-01-19 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('rango', models.PositiveIntegerField(max_length=5, verbose_name='rango')),
                ('duracion', models.PositiveIntegerField(verbose_name='duracion')),
                ('imagen', models.TextField(verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('edad', models.PositiveIntegerField(verbose_name='edad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.pelicula')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
    ]
